version: "3.9"
services:
  artemis:
    build: "./Artemis"
    container_name: "artemis"
    # Persistent volume
    # Make sure you prune to get clean state for test runs
    volumes:
      - artemis-data:/var/lib/artemis/data
    ports:
      - "8161:8161"
    # You can set up limits here
    # But make sure you also correct java memory in artemis Dockerfile in order to have effect.
    deploy:
      resources:
        reservations:
          memory: 8g

  producer-idnes.cz:
    # This is the producer service, you can have multiple of them
    build: "./Aggregator"
    command: [ "idnes.cz" ]
    depends_on:
      - consumer

  producer-aktualne.cz:
    build: "./Aggregator"
    command: [ "aktualne.cz" ]
    depends_on:
      - consumer
  
  producer-ihned.cz:
    build: "./Aggregator"
    command: [ "ihned.cz" ]
    depends_on:
      - consumer

  producer-novinky.cz:
    build: "./Aggregator"
    command: [ "novinky.cz" ]
    depends_on:
      - consumer
  
  producer-irozhlas.cz:
    build: ./Aggregator
    command: [ "irozhlas.cz" ]
    depends_on:
      - consumer

  producer-seznamzpravy.cz:
    build: "./Aggregator"
    command: ["seznamzpravy.cz"]
    depends_on:
      - consumer

  producer-denik.cz:
    build: "./Aggregator"
    command: ["denik.cz"]
    depends_on:
      - consumer


  # This is consumer spawn as many as you want, you ideally want to have pills set up to number of producers.
  # Make sure you use use-hostname-output to have disitnguished output folders for each consumer.
  consumer:
    build: ./Processor
    command:
      [
        "--use_hostname_output",
        "--timeout=1",
        "--pills_to_die=7",
        "--queue_size=200",
        "queue.idnes.cz",
        "queue.aktualne.cz",
        "queue.ihned.cz",
        "queue.novinky.cz",
        "queue.irozhlas.cz",
        "queue.seznamzpravy.cz",
        "queue.denik.cz",

      ]
    volumes:
      - ./output:/output:z
    deploy:
      # Number of replicas
      replicas: 50
    depends_on:
      - artemis

volumes:
  artemis-data:
